"""
builders/copilot.py
Builds GitHub Copilot instruction files and ignore files.

Output:
  {output}/.github/copilot-instructions.md         ← always-on rules
  {output}/.github/instructions/{mode}.instructions.md  ← per-mode with applyTo
  {output}/.copilotignore                         ← ignore patterns
  {output}/.gitignore                             ← standard git ignore patterns
"""

from datetime import datetime
from pathlib import Path
from typing import Any

from promptosaurus.builders.builder import Builder
from promptosaurus.registry import registry


class CopilotBuilder(Builder):
    """Builder for GitHub Copilot instruction files."""

    def build(
        self, output: Path, config: dict[str, Any] | None = None, dry_run: bool = False
    ) -> list[str]:
        """
        Write Copilot instruction files under `output`.
        Returns a list of action strings for display.
        """
        actions: list[str] = []
        github = output / ".github"

        # Always-on: copilot-instructions.md
        actions.extend(self._build_always_on(github, dry_run))

        # Per-mode instruction files
        for mode_key, files in registry.mode_files.items():
            actions.extend(self._build_mode(github, mode_key, files, dry_run))

        # Build .copilotignore
        actions.extend(self._build_copilotignore(output, dry_run))

        # Build .gitignore
        actions.extend(self._build_gitignore(output, dry_run))

        return actions

    def _build_always_on(self, github: Path, dry_run: bool) -> list[str]:
        destination = github / "copilot-instructions.md"
        now = datetime.now().strftime("%Y-%m-%d %H:%M")
        lines: list[str] = [
            "# GitHub Copilot Instructions",
            "# Auto-generated by prompt CLI — edit files in prompts/ then rebuild",
            f"# Last built: {now}",
            "",
        ]
        for filename in registry.always_on:
            try:
                body = registry.prompt_body(filename)
            except FileNotFoundError:
                lines.append(f"<!-- MISSING: {filename} -->")
                continue
            lines.append("---")
            lines.append(body.rstrip())
            lines.append("")

        content = "\n".join(lines) + "\n"

        if dry_run:
            return ["[dry-run] .github/copilot-instructions.md"]

        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8")
        return ["✓ .github/copilot-instructions.md"]

    def _build_mode(
        self,
        github: Path,
        mode_key: str,
        files: list[str],
        dry_run: bool,
    ) -> list[str]:
        destination = github / "instructions" / f"{mode_key}.instructions.md"
        label = registry.modes.get(mode_key, mode_key.title())
        apply = registry.copilot_apply.get(mode_key, "**")

        lines: list[str] = [
            "---",
            f"applyTo: '{apply}'",
            "---",
            f"# {label} Mode Instructions",
            "",
        ]
        for filename in files:
            try:
                body = registry.prompt_body(filename)
            except FileNotFoundError:
                lines.append(f"<!-- MISSING: {filename} -->")
                continue
            lines.append(body.rstrip())
            lines.append("")

        content = "\n".join(lines) + "\n"

        if dry_run:
            return [f"[dry-run] .github/instructions/{mode_key}.instructions.md"]

        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8")
        return [f"✓ .github/instructions/{mode_key}.instructions.md"]

    def _build_copilotignore(self, output: Path, dry_run: bool) -> list[str]:
        """Generate .copilotignore file."""
        destination = output / ".copilotignore"
        content = registry.generate_copilotignore()

        if dry_run:
            lines = content.count("\n")
            return [f"[dry-run] .copilotignore ({lines} lines)"]

        destination.write_text(content, encoding="utf-8")
        lines = content.count("\n")
        return [f"✓ .copilotignore ({lines} lines)"]

    def _build_gitignore(self, output: Path, dry_run: bool) -> list[str]:
        """Generate .gitignore file."""
        destination = output / ".gitignore"
        content = registry.generate_gitignore()

        if dry_run:
            lines = content.count("\n")
            return [f"[dry-run] .gitignore ({lines} lines)"]

        destination.write_text(content, encoding="utf-8")
        lines = content.count("\n")
        return [f"✓ .gitignore ({lines} lines)"]
