"""
builders/_concat.py
Shared helper: builds a single concatenated markdown string from all prompt
files in concat_order, with section headers between each.

Used by Cline (.clinerules), Cursor (.cursorrules legacy), and Copilot
(copilot-instructions.md always-on section).
"""

from datetime import datetime

from promptcli.registry import registry


def build_concatenated(tool_comment: str) -> str:
    """
    Returns the full text of a concatenated rules file.

    tool_comment: first-line comment, e.g. '# .clinerules'
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines: list[str] = [
        tool_comment,
        "# Auto-generated by prompt CLI — edit files in prompts/ then rebuild",
        f"# Last built: {now}",
        "",
    ]

    for label, filename in registry.concat_order:
        try:
            body = registry.prompt_body(filename)
        except FileNotFoundError:
            lines.append(f"## {label} — MISSING: {filename}")
            lines.append("")
            continue

        lines.append("---")
        lines.append(f"## {label}")
        lines.append("")
        lines.append(body.rstrip())
        lines.append("")

    return "\n".join(lines) + "\n"
