"""
builders/copilot.py
Builds GitHub Copilot instruction files.

Output:
  {output}/.github/copilot-instructions.md         ← always-on rules
  {output}/.github/instructions/{mode}.instructions.md  ← per-mode with applyTo
"""

from datetime import datetime
from pathlib import Path

from promptcli.builders.builder import Builder
from promptcli.registry import (
    ALWAYS_ON,
    COPILOT_APPLY,
    MODE_FILES,
    MODES,
    prompt_body,
)


class CopilotBuilder(Builder):
    """Builder for GitHub Copilot instruction files."""

    def build(self, output: Path, dry_run: bool = False) -> list[str]:
        """
        Write Copilot instruction files under `output`.
        Returns a list of action strings for display.
        """
        actions: list[str] = []
        github = output / ".github"

        # Always-on: copilot-instructions.md
        actions.extend(self._build_always_on(github, dry_run))

        # Per-mode instruction files
        for mode_key, files in MODE_FILES.items():
            actions.extend(self._build_mode(github, mode_key, files, dry_run))

        return actions

    def _build_always_on(self, github: Path, dry_run: bool) -> list[str]:
        dst = github / "copilot-instructions.md"
        now = datetime.now().strftime("%Y-%m-%d %H:%M")
        lines: list[str] = [
            "# GitHub Copilot Instructions",
            "# Auto-generated by prompt CLI — edit files in prompts/ then rebuild",
            f"# Last built: {now}",
            "",
        ]
        for filename in ALWAYS_ON:
            try:
                body = prompt_body(filename)
            except FileNotFoundError:
                lines.append(f"<!-- MISSING: {filename} -->")
                continue
            lines.append("---")
            lines.append(body.rstrip())
            lines.append("")

        content = "\n".join(lines) + "\n"

        if dry_run:
            return ["[dry-run] .github/copilot-instructions.md"]

        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(content, encoding="utf-8")
        return ["✓ .github/copilot-instructions.md"]

    def _build_mode(
        self,
        github: Path,
        mode_key: str,
        files: list[str],
        dry_run: bool,
    ) -> list[str]:
        dst = github / "instructions" / f"{mode_key}.instructions.md"
        label = MODES.get(mode_key, mode_key.title())
        apply = COPILOT_APPLY.get(mode_key, "**")

        lines: list[str] = [
            "---",
            f"applyTo: '{apply}'",
            "---",
            f"# {label} Mode Instructions",
            "",
        ]
        for filename in files:
            try:
                body = prompt_body(filename)
            except FileNotFoundError:
                lines.append(f"<!-- MISSING: {filename} -->")
                continue
            lines.append(body.rstrip())
            lines.append("")

        content = "\n".join(lines) + "\n"

        if dry_run:
            return [f"[dry-run] .github/instructions/{mode_key}.instructions.md"]

        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(content, encoding="utf-8")
        return [f"✓ .github/instructions/{mode_key}.instructions.md"]
